//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrations.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Migrations.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC sp_MSforeachtable @command1=&quot;ALTER TABLE ? DISABLE TRIGGER ALL&quot;
        ///GO
        ///-- SQL disable all constraints - disable all constraints sql server
        ///EXEC sp_MSforeachtable @command1=&quot;ALTER TABLE ? NOCHECK CONSTRAINT ALL&quot;
        ///GO
        ///SET IDENTITY_INSERT [dbo].[cmsDictionary] ON
        ///INSERT [dbo].[cmsDictionary] ([pk], [id], [parent], [key]) VALUES (5, N&apos;3d96d964-1e4c-407c-9c8d-4fc0cc962d11&apos;, N&apos;41c7638d-f529-4bff-853e-59a0c2fb1bde&apos;, N&apos;ArtistName&apos;)
        ///INSERT [dbo].[cmsDictionary] ([pk], [id], [parent], [key]) VALUES (6, N&apos;a2a7aa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CreateData {
            get {
                return ResourceManager.GetString("CreateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT loginname FROM master.dbo.syslogins WHERE name = &apos;{1}&apos;)
        ///BEGIN
        ///    CREATE LOGIN {1}
        ///    WITH PASSWORD = &apos;{2}&apos;;
        ///END
        ///GO
        ///USE [{0}];
        ///CREATE USER [{1}] FOR LOGIN [{1}] 
        ///GO
        ///ALTER AUTHORIZATION ON SCHEMA::[db_owner] TO [{1}] 
        ///GO 
        ///EXEC sp_addrolemember N&apos;db_owner&apos;, N&apos;{1}&apos;
        ///GO.
        /// </summary>
        public static string CreateDefaultUser {
            get {
                return ResourceManager.GetString("CreateDefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[CMSImportState](
        ///	[Id] [int] IDENTITY(1,1) NOT NULL,
        ///	[UniqueIdentifier] [uniqueidentifier] NOT NULL,
        ///	[Name] [nvarchar](250) NOT NULL,
        ///	[ImportType] [nvarchar](250) NOT NULL,
        ///	[ImportState] [nvarchar](max) NOT NULL,
        ///	[Recursive] [bit] NULL,
        ///	[Parent] [uniqueidentifier] NULL,
        /// CONSTRAINT [PK_CMSImportState] PRIMARY KEY CLUSTERED 
        ///(
        ///	[Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY] [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CreateSchema {
            get {
                return ResourceManager.GetString("CreateSchema", resourceCulture);
            }
        }
    }
}
