//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Migrations.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Migrations.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [universaljp-working]
        ///GO
        ////****** Object:  Table [dbo].[CMSImportState]    Script Date: 03/07/2012 11:10:57 ******/
        ////****** Object:  Table [dbo].[CMSImportScheduledTask]    Script Date: 03/07/2012 11:10:57 ******/
        ////****** Object:  Table [dbo].[CMSImportScheduledItems]    Script Date: 03/07/2012 11:10:57 ******/
        ////****** Object:  Table [dbo].[CMSImportRelation]    Script Date: 03/07/2012 11:10:57 ******/
        ////****** Object:  Table [dbo].[CMSImportMediaRelation]    Script Date: 03/07/2012 11:10:57 ******/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateData {
            get {
                return ResourceManager.GetString("CreateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT loginname FROM master.dbo.syslogins WHERE name = &apos;{1}&apos;)
        ///BEGIN
        ///    CREATE LOGIN {1}
        ///    WITH PASSWORD = &apos;{2}&apos;;
        ///END
        ///GO
        ///USE {0};
        ///    CREATE USER {1} FOR LOGIN {1}
        ///    WITH DEFAULT_SCHEMA = dbo;
        ///GO
        ///.
        /// </summary>
        internal static string CreateDefaultUser {
            get {
                return ResourceManager.GetString("CreateDefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [master]
        ///GO
        ////****** Object:  Database [universaljp-working]    Script Date: 03/07/2012 10:50:57 ******/
        ///CREATE DATABASE [universaljp-working] ON  PRIMARY 
        ///( NAME = N&apos;dev.japan.local&apos;, FILENAME = N&apos;c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\universaljp.mdf&apos; , SIZE = 79872KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
        /// LOG ON 
        ///( NAME = N&apos;dev.japan.local_log&apos;, FILENAME = N&apos;c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\universaljp_1.ldf&apos; , SIZE = 517184K [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateSchema {
            get {
                return ResourceManager.GetString("CreateSchema", resourceCulture);
            }
        }
    }
}
